---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-service
spec:
  selector:
    app: {{ .Chart.Name }}
    track: {{ .Values.track | default "blue" | quote}}
  ports:
  - port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-deployment
  labels:
    app: {{ .Chart.Name }}
    track: {{ .Values.track | default "blue" | quote}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      track: {{ .Values.track }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        # image: "{{ template "helloworld.image" . }}"
        image: ray99chen/helloworld:v2
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: helloworld-config
        ports:
        - containerPort: 8080
---
